package com.bupt.ctrl.model;

public class Chapter {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdrb..chapter.Chapter_id
     *
     * @mbggenerated Wed Jul 10 09:55:09 CST 2019
     */
    private Integer chapterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdrb..chapter.Chapter_Num
     *
     * @mbggenerated Wed Jul 10 09:55:09 CST 2019
     */
    private Integer chapterNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdrb..chapter.Chapter_Name
     *
     * @mbggenerated Wed Jul 10 09:55:09 CST 2019
     */
    private String chapterName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdrb..chapter.Chapter_Video
     *
     * @mbggenerated Wed Jul 10 09:55:09 CST 2019
     */
    private String chapterVideo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdrb..chapter.Chapter_PPT
     *
     * @mbggenerated Wed Jul 10 09:55:09 CST 2019
     */
    private String chapterPpt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdrb..chapter.Course_Course_Id
     *
     * @mbggenerated Wed Jul 10 09:55:09 CST 2019
     */
    private Integer courseCourseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdrb..chapter.Chapter_Intro
     *
     * @mbggenerated Wed Jul 10 09:55:09 CST 2019
     */
    private String chapterIntro;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdrb..chapter.Chapter_id
     *
     * @return the value of sdrb..chapter.Chapter_id
     *
     * @mbggenerated Wed Jul 10 09:55:09 CST 2019
     */
    public Integer getChapterId() {
        return chapterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdrb..chapter.Chapter_id
     *
     * @param chapterId the value for sdrb..chapter.Chapter_id
     *
     * @mbggenerated Wed Jul 10 09:55:09 CST 2019
     */
    public void setChapterId(Integer chapterId) {
        this.chapterId = chapterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdrb..chapter.Chapter_Num
     *
     * @return the value of sdrb..chapter.Chapter_Num
     *
     * @mbggenerated Wed Jul 10 09:55:09 CST 2019
     */
    public Integer getChapterNum() {
        return chapterNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdrb..chapter.Chapter_Num
     *
     * @param chapterNum the value for sdrb..chapter.Chapter_Num
     *
     * @mbggenerated Wed Jul 10 09:55:09 CST 2019
     */
    public void setChapterNum(Integer chapterNum) {
        this.chapterNum = chapterNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdrb..chapter.Chapter_Name
     *
     * @return the value of sdrb..chapter.Chapter_Name
     *
     * @mbggenerated Wed Jul 10 09:55:09 CST 2019
     */
    public String getChapterName() {
        return chapterName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdrb..chapter.Chapter_Name
     *
     * @param chapterName the value for sdrb..chapter.Chapter_Name
     *
     * @mbggenerated Wed Jul 10 09:55:09 CST 2019
     */
    public void setChapterName(String chapterName) {
        this.chapterName = chapterName == null ? null : chapterName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdrb..chapter.Chapter_Video
     *
     * @return the value of sdrb..chapter.Chapter_Video
     *
     * @mbggenerated Wed Jul 10 09:55:09 CST 2019
     */
    public String getChapterVideo() {
        return chapterVideo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdrb..chapter.Chapter_Video
     *
     * @param chapterVideo the value for sdrb..chapter.Chapter_Video
     *
     * @mbggenerated Wed Jul 10 09:55:09 CST 2019
     */
    public void setChapterVideo(String chapterVideo) {
        this.chapterVideo = chapterVideo == null ? null : chapterVideo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdrb..chapter.Chapter_PPT
     *
     * @return the value of sdrb..chapter.Chapter_PPT
     *
     * @mbggenerated Wed Jul 10 09:55:09 CST 2019
     */
    public String getChapterPpt() {
        return chapterPpt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdrb..chapter.Chapter_PPT
     *
     * @param chapterPpt the value for sdrb..chapter.Chapter_PPT
     *
     * @mbggenerated Wed Jul 10 09:55:09 CST 2019
     */
    public void setChapterPpt(String chapterPpt) {
        this.chapterPpt = chapterPpt == null ? null : chapterPpt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdrb..chapter.Course_Course_Id
     *
     * @return the value of sdrb..chapter.Course_Course_Id
     *
     * @mbggenerated Wed Jul 10 09:55:09 CST 2019
     */
    public Integer getCourseCourseId() {
        return courseCourseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdrb..chapter.Course_Course_Id
     *
     * @param courseCourseId the value for sdrb..chapter.Course_Course_Id
     *
     * @mbggenerated Wed Jul 10 09:55:09 CST 2019
     */
    public void setCourseCourseId(Integer courseCourseId) {
        this.courseCourseId = courseCourseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdrb..chapter.Chapter_Intro
     *
     * @return the value of sdrb..chapter.Chapter_Intro
     *
     * @mbggenerated Wed Jul 10 09:55:09 CST 2019
     */
    public String getChapterIntro() {
        return chapterIntro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdrb..chapter.Chapter_Intro
     *
     * @param chapterIntro the value for sdrb..chapter.Chapter_Intro
     *
     * @mbggenerated Wed Jul 10 09:55:09 CST 2019
     */
    public void setChapterIntro(String chapterIntro) {
        this.chapterIntro = chapterIntro == null ? null : chapterIntro.trim();
    }
}