package com.bupt.ctrl.model;

import java.util.Date;

public class Comment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdrb..comment.Comment_id
     *
     * @mbggenerated Wed Jul 10 09:55:09 CST 2019
     */
    private Integer commentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdrb..comment.Comment_Content
     *
     * @mbggenerated Wed Jul 10 09:55:09 CST 2019
     */
    private String commentContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdrb..comment.Comment_Time
     *
     * @mbggenerated Wed Jul 10 09:55:09 CST 2019
     */
    private Date commentTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdrb..comment.Comment_To
     *
     * @mbggenerated Wed Jul 10 09:55:09 CST 2019
     */
    private Integer commentTo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdrb..comment.Chapter_Chapter_id
     *
     * @mbggenerated Wed Jul 10 09:55:09 CST 2019
     */
    private Integer chapterChapterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdrb..comment.User_User_id
     *
     * @mbggenerated Wed Jul 10 09:55:09 CST 2019
     */
    private Integer userUserId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdrb..comment.Comment_id
     *
     * @return the value of sdrb..comment.Comment_id
     *
     * @mbggenerated Wed Jul 10 09:55:09 CST 2019
     */
    public Integer getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdrb..comment.Comment_id
     *
     * @param commentId the value for sdrb..comment.Comment_id
     *
     * @mbggenerated Wed Jul 10 09:55:09 CST 2019
     */
    public void setCommentId(Integer commentId) {
        this.commentId = commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdrb..comment.Comment_Content
     *
     * @return the value of sdrb..comment.Comment_Content
     *
     * @mbggenerated Wed Jul 10 09:55:09 CST 2019
     */
    public String getCommentContent() {
        return commentContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdrb..comment.Comment_Content
     *
     * @param commentContent the value for sdrb..comment.Comment_Content
     *
     * @mbggenerated Wed Jul 10 09:55:09 CST 2019
     */
    public void setCommentContent(String commentContent) {
        this.commentContent = commentContent == null ? null : commentContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdrb..comment.Comment_Time
     *
     * @return the value of sdrb..comment.Comment_Time
     *
     * @mbggenerated Wed Jul 10 09:55:09 CST 2019
     */
    public Date getCommentTime() {
        return commentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdrb..comment.Comment_Time
     *
     * @param commentTime the value for sdrb..comment.Comment_Time
     *
     * @mbggenerated Wed Jul 10 09:55:09 CST 2019
     */
    public void setCommentTime(Date commentTime) {
        this.commentTime = commentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdrb..comment.Comment_To
     *
     * @return the value of sdrb..comment.Comment_To
     *
     * @mbggenerated Wed Jul 10 09:55:09 CST 2019
     */
    public Integer getCommentTo() {
        return commentTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdrb..comment.Comment_To
     *
     * @param commentTo the value for sdrb..comment.Comment_To
     *
     * @mbggenerated Wed Jul 10 09:55:09 CST 2019
     */
    public void setCommentTo(Integer commentTo) {
        this.commentTo = commentTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdrb..comment.Chapter_Chapter_id
     *
     * @return the value of sdrb..comment.Chapter_Chapter_id
     *
     * @mbggenerated Wed Jul 10 09:55:09 CST 2019
     */
    public Integer getChapterChapterId() {
        return chapterChapterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdrb..comment.Chapter_Chapter_id
     *
     * @param chapterChapterId the value for sdrb..comment.Chapter_Chapter_id
     *
     * @mbggenerated Wed Jul 10 09:55:09 CST 2019
     */
    public void setChapterChapterId(Integer chapterChapterId) {
        this.chapterChapterId = chapterChapterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdrb..comment.User_User_id
     *
     * @return the value of sdrb..comment.User_User_id
     *
     * @mbggenerated Wed Jul 10 09:55:09 CST 2019
     */
    public Integer getUserUserId() {
        return userUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdrb..comment.User_User_id
     *
     * @param userUserId the value for sdrb..comment.User_User_id
     *
     * @mbggenerated Wed Jul 10 09:55:09 CST 2019
     */
    public void setUserUserId(Integer userUserId) {
        this.userUserId = userUserId;
    }
}