package com.bupt.ctrl.model;

import java.util.Date;

public class Course {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdrb..course.Course_Id
     *
     * @mbggenerated Wed Jul 10 09:55:09 CST 2019
     */
    private Integer courseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdrb..course.Course_Name
     *
     * @mbggenerated Wed Jul 10 09:55:09 CST 2019
     */
    private String courseName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdrb..course.Course_Pass
     *
     * @mbggenerated Wed Jul 10 09:55:09 CST 2019
     */
    private Integer coursePass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdrb..course.Course_Intro
     *
     * @mbggenerated Wed Jul 10 09:55:09 CST 2019
     */
    private String courseIntro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdrb..course.Course_Image
     *
     * @mbggenerated Wed Jul 10 09:55:09 CST 2019
     */
    private String courseImage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdrb..course.Course_Date
     *
     * @mbggenerated Wed Jul 10 09:55:09 CST 2019
     */
    private Date courseDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdrb..course.Course_Teacher
     *
     * @mbggenerated Wed Jul 10 09:55:09 CST 2019
     */
    private String courseTeacher;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdrb..course.Course_Id
     *
     * @return the value of sdrb..course.Course_Id
     *
     * @mbggenerated Wed Jul 10 09:55:09 CST 2019
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdrb..course.Course_Id
     *
     * @param courseId the value for sdrb..course.Course_Id
     *
     * @mbggenerated Wed Jul 10 09:55:09 CST 2019
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdrb..course.Course_Name
     *
     * @return the value of sdrb..course.Course_Name
     *
     * @mbggenerated Wed Jul 10 09:55:09 CST 2019
     */
    public String getCourseName() {
        return courseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdrb..course.Course_Name
     *
     * @param courseName the value for sdrb..course.Course_Name
     *
     * @mbggenerated Wed Jul 10 09:55:09 CST 2019
     */
    public void setCourseName(String courseName) {
        this.courseName = courseName == null ? null : courseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdrb..course.Course_Pass
     *
     * @return the value of sdrb..course.Course_Pass
     *
     * @mbggenerated Wed Jul 10 09:55:09 CST 2019
     */
    public Integer getCoursePass() {
        return coursePass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdrb..course.Course_Pass
     *
     * @param coursePass the value for sdrb..course.Course_Pass
     *
     * @mbggenerated Wed Jul 10 09:55:09 CST 2019
     */
    public void setCoursePass(Integer coursePass) {
        this.coursePass = coursePass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdrb..course.Course_Intro
     *
     * @return the value of sdrb..course.Course_Intro
     *
     * @mbggenerated Wed Jul 10 09:55:09 CST 2019
     */
    public String getCourseIntro() {
        return courseIntro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdrb..course.Course_Intro
     *
     * @param courseIntro the value for sdrb..course.Course_Intro
     *
     * @mbggenerated Wed Jul 10 09:55:09 CST 2019
     */
    public void setCourseIntro(String courseIntro) {
        this.courseIntro = courseIntro == null ? null : courseIntro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdrb..course.Course_Image
     *
     * @return the value of sdrb..course.Course_Image
     *
     * @mbggenerated Wed Jul 10 09:55:09 CST 2019
     */
    public String getCourseImage() {
        return courseImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdrb..course.Course_Image
     *
     * @param courseImage the value for sdrb..course.Course_Image
     *
     * @mbggenerated Wed Jul 10 09:55:09 CST 2019
     */
    public void setCourseImage(String courseImage) {
        this.courseImage = courseImage == null ? null : courseImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdrb..course.Course_Date
     *
     * @return the value of sdrb..course.Course_Date
     *
     * @mbggenerated Wed Jul 10 09:55:09 CST 2019
     */
    public Date getCourseDate() {
        return courseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdrb..course.Course_Date
     *
     * @param courseDate the value for sdrb..course.Course_Date
     *
     * @mbggenerated Wed Jul 10 09:55:09 CST 2019
     */
    public void setCourseDate(Date courseDate) {
        this.courseDate = courseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdrb..course.Course_Teacher
     *
     * @return the value of sdrb..course.Course_Teacher
     *
     * @mbggenerated Wed Jul 10 09:55:09 CST 2019
     */
    public String getCourseTeacher() {
        return courseTeacher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdrb..course.Course_Teacher
     *
     * @param courseTeacher the value for sdrb..course.Course_Teacher
     *
     * @mbggenerated Wed Jul 10 09:55:09 CST 2019
     */
    public void setCourseTeacher(String courseTeacher) {
        this.courseTeacher = courseTeacher == null ? null : courseTeacher.trim();
    }
}