package com.bupt.ctrl.model;

public class UserHasChapterKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdrb..user_has_chapter.User_User_id
     *
     * @mbggenerated Wed Jul 10 09:55:09 CST 2019
     */
    private Integer userUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdrb..user_has_chapter.Chapter_Chapter_id
     *
     * @mbggenerated Wed Jul 10 09:55:09 CST 2019
     */
    private Integer chapterChapterId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdrb..user_has_chapter.User_User_id
     *
     * @return the value of sdrb..user_has_chapter.User_User_id
     *
     * @mbggenerated Wed Jul 10 09:55:09 CST 2019
     */
    public Integer getUserUserId() {
        return userUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdrb..user_has_chapter.User_User_id
     *
     * @param userUserId the value for sdrb..user_has_chapter.User_User_id
     *
     * @mbggenerated Wed Jul 10 09:55:09 CST 2019
     */
    public void setUserUserId(Integer userUserId) {
        this.userUserId = userUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdrb..user_has_chapter.Chapter_Chapter_id
     *
     * @return the value of sdrb..user_has_chapter.Chapter_Chapter_id
     *
     * @mbggenerated Wed Jul 10 09:55:09 CST 2019
     */
    public Integer getChapterChapterId() {
        return chapterChapterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdrb..user_has_chapter.Chapter_Chapter_id
     *
     * @param chapterChapterId the value for sdrb..user_has_chapter.Chapter_Chapter_id
     *
     * @mbggenerated Wed Jul 10 09:55:09 CST 2019
     */
    public void setChapterChapterId(Integer chapterChapterId) {
        this.chapterChapterId = chapterChapterId;
    }
}