package com.bupt.ctrl.model;

public class UserHasChapter extends UserHasChapterKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdrb..user_has_chapter.User_has_Learned
     *
     * @mbggenerated Mon Jul 08 08:22:52 CST 2019
     */
    private Integer userHasLearned;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdrb..user_has_chapter.User_has_Learned
     *
     * @return the value of sdrb..user_has_chapter.User_has_Learned
     *
     * @mbggenerated Mon Jul 08 08:22:52 CST 2019
     */
    public Integer getUserHasLearned() {
        return userHasLearned;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdrb..user_has_chapter.User_has_Learned
     *
     * @param userHasLearned the value for sdrb..user_has_chapter.User_has_Learned
     *
     * @mbggenerated Mon Jul 08 08:22:52 CST 2019
     */
    public void setUserHasLearned(Integer userHasLearned) {
        this.userHasLearned = userHasLearned;
    }
}