package com.bupt.ctrl.model;

public class UserHasCourse {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdrb..user_has_course.Course_Course_Id
     *
     * @mbggenerated Mon Jul 08 08:22:52 CST 2019
     */
    private Integer courseCourseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdrb..user_has_course.User_Teachorstudy
     *
     * @mbggenerated Mon Jul 08 08:22:52 CST 2019
     */
    private Integer userTeachorstudy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdrb..user_has_course.User_User_id
     *
     * @mbggenerated Mon Jul 08 08:22:52 CST 2019
     */
    private Integer userUserId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdrb..user_has_course.Course_Course_Id
     *
     * @return the value of sdrb..user_has_course.Course_Course_Id
     *
     * @mbggenerated Mon Jul 08 08:22:52 CST 2019
     */
    public Integer getCourseCourseId() {
        return courseCourseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdrb..user_has_course.Course_Course_Id
     *
     * @param courseCourseId the value for sdrb..user_has_course.Course_Course_Id
     *
     * @mbggenerated Mon Jul 08 08:22:52 CST 2019
     */
    public void setCourseCourseId(Integer courseCourseId) {
        this.courseCourseId = courseCourseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdrb..user_has_course.User_Teachorstudy
     *
     * @return the value of sdrb..user_has_course.User_Teachorstudy
     *
     * @mbggenerated Mon Jul 08 08:22:52 CST 2019
     */
    public Integer getUserTeachorstudy() {
        return userTeachorstudy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdrb..user_has_course.User_Teachorstudy
     *
     * @param userTeachorstudy the value for sdrb..user_has_course.User_Teachorstudy
     *
     * @mbggenerated Mon Jul 08 08:22:52 CST 2019
     */
    public void setUserTeachorstudy(Integer userTeachorstudy) {
        this.userTeachorstudy = userTeachorstudy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdrb..user_has_course.User_User_id
     *
     * @return the value of sdrb..user_has_course.User_User_id
     *
     * @mbggenerated Mon Jul 08 08:22:52 CST 2019
     */
    public Integer getUserUserId() {
        return userUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdrb..user_has_course.User_User_id
     *
     * @param userUserId the value for sdrb..user_has_course.User_User_id
     *
     * @mbggenerated Mon Jul 08 08:22:52 CST 2019
     */
    public void setUserUserId(Integer userUserId) {
        this.userUserId = userUserId;
    }
}