package com.bupt.ctrl.dao;

import com.bupt.ctrl.model.Comment;
import com.bupt.ctrl.model.CommentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdrb..comment
     *
     * @mbggenerated Fri Jul 05 08:34:32 CST 2019
     */
    int countByExample(CommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdrb..comment
     *
     * @mbggenerated Fri Jul 05 08:34:32 CST 2019
     */
    int deleteByExample(CommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdrb..comment
     *
     * @mbggenerated Fri Jul 05 08:34:32 CST 2019
     */
    int deleteByPrimaryKey(Integer commentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdrb..comment
     *
     * @mbggenerated Fri Jul 05 08:34:32 CST 2019
     */
    int insert(Comment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdrb..comment
     *
     * @mbggenerated Fri Jul 05 08:34:32 CST 2019
     */
    int insertSelective(Comment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdrb..comment
     *
     * @mbggenerated Fri Jul 05 08:34:32 CST 2019
     */
    List<Comment> selectByExample(CommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdrb..comment
     *
     * @mbggenerated Fri Jul 05 08:34:32 CST 2019
     */
    Comment selectByPrimaryKey(Integer commentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdrb..comment
     *
     * @mbggenerated Fri Jul 05 08:34:32 CST 2019
     */
    int updateByExampleSelective(@Param("record") Comment record, @Param("example") CommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdrb..comment
     *
     * @mbggenerated Fri Jul 05 08:34:32 CST 2019
     */
    int updateByExample(@Param("record") Comment record, @Param("example") CommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdrb..comment
     *
     * @mbggenerated Fri Jul 05 08:34:32 CST 2019
     */
    int updateByPrimaryKeySelective(Comment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdrb..comment
     *
     * @mbggenerated Fri Jul 05 08:34:32 CST 2019
     */
    int updateByPrimaryKey(Comment record);
}